<a href="https://colab.research.google.com/github/sararanjbarz/iris-datasets--Covar/blob/main/Homework01_Covar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
data= datasets.load_iris()

df = pd.DataFrame(data.data,columns=data.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [47]:

df['target']= data.target
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [48]:
data= df.to_numpy()[:,:2]

data.shape

(150, 2)

In [49]:
def descritisize(x1,x2):
  x=7*[0]
  if  4.3<= x1 <=5.2: x[0]=1
  if  5.2< x1 <=6.1: x[1] =1
  if  6.1< x1 <=7.0: x[2] =1
  if  7.0< x1 <=7.9: x[3] =1
  if  2.0<= x2 <=2.8: x[4] =1
  if  2.8< x2 <=3.6: x[5] =1
  if  3.6< x2 <=4.4: x[6] =1

  return np.array(x)

In [50]:
descritisize(data[0,0],data[0,1])

array([1, 0, 0, 0, 0, 1, 0])

In [51]:
mu = np.array(7*[0])
for x in data:
  mu= mu + descritisize(x[0],x[1])

mu

array([45, 50, 43, 12, 47, 88, 15])

In [52]:
mu= mu/150
print(mu.round(2))

[0.3  0.33 0.29 0.08 0.31 0.59 0.1 ]


Covariance Matrix



In [54]:
N12 = np.full((4,3),0)
N1 = np.full((4,1),0)
N2 = np.full((3,1),0)

for x in data:
    x = descritisize(x[0],x[1])
    x1 = x[:4].reshape((4,1))
    x2 = x[-3:].reshape((3,1))
    N12 = N12 + x1 @ x2.T
    N1 = N1 + x1
    N2 = N2 + x2

p1 = N1/150
p2 = N2/150
P12 = N12/150

mu = np.vstack((p1,p2))

P1 = np.diagflat(p1)
P2 = np.diagflat(p2)

S11 = P1-p1@p1.T
S22 = P2-p2@p2.T
S12 = P12 - p1@p2.T
S21 = S12.T

S1 = np.hstack((S11,S12))
S2 = np.hstack((S21,S22))
S = np.vstack((S1,S2))

print(mu.round(3))
print(S.round(3))

[[0.3  ]
 [0.333]
 [0.287]
 [0.08 ]
 [0.313]
 [0.587]
 [0.1  ]]
[[ 0.21  -0.1   -0.086 -0.024 -0.047  0.044  0.003]
 [-0.1    0.222 -0.096 -0.027  0.056 -0.076  0.02 ]
 [-0.086 -0.096  0.204 -0.023 -0.003  0.032 -0.029]
 [-0.024 -0.027 -0.023  0.074 -0.005 -0.     0.005]
 [-0.047  0.056 -0.003 -0.005  0.215 -0.184 -0.031]
 [ 0.044 -0.076  0.032 -0.    -0.184  0.242 -0.059]
 [ 0.003  0.02  -0.029  0.005 -0.031 -0.059  0.09 ]]
